print("Welcome to the tip calculator!\n")
total_bill = float(input("What was the total bill? $"))
tip_percent = int(input("What percentage tip would you like to give? 10, 12 or 15? "))
people_num = int(input("How many people to split the bill? "))
calculation = (total_bill) / (people_num) * (1 + (tip_percent) / 100)
final_answer = "{:.2f}".format(calculation)
print(f"Each person should pay: ${final_answer}")
